language: python
python:
  - 3.7
  
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

# install packages
install:
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose pip coverage
  - source activate testenv
  - python setup.py install

script:
 - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then python -m unittest discover; fi
 
notifications:
  email: 
    - mohamed@kuicr.kyoto-u.ac.jp
